export const KEY_WORD = 'KEY_WORD';

export const GET_MENU = 'GET_MENU';

export const SHOW_MESSAGE_REQUEST = 'SHOW_MESSAGE_REQUEST';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

export const FETCH_REPOSITORIES_REQUEST = 'FETCH_REPOSITORIES_REQUEST';
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';

export const FETCH_REPOSITORY_REQUEST = 'FETCH_REPOSITORY_REQUEST';
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS';

export const FETCH_REPOSITORY_LANGUAGE_REQUEST = 'FETCH_REPOSITORY_LANGUAGE_REQUEST';
export const FETCH_REPOSITORY_LANGUAGE_SUCCESS = 'FETCH_REPOSITORY_LANGUAGE_SUCCESS';

export const FETCH_REPOSITORY_COMMITS_REQUEST = 'FETCH_REPOSITORY_COMMITS_REQUEST';
export const FETCH_REPOSITORY_COMMITS_SUCCESS = 'FETCH_REPOSITORY_COMMITS_SUCCESS';

export const FETCH_REPOSITORY_BRANCHES_REQUEST = 'FETCH_REPOSITORY_BRANCHES_REQUEST';
export const FETCH_REPOSITORY_BRANCHES_SUCCESS = 'FETCH_REPOSITORY_BRANCHES_SUCCESS';

export const FETCH_REPOSITORY_CONTRIBUTORS_REQUEST = 'FETCH_REPOSITORY_CONTRIBUTORS_REQUEST';
export const FETCH_REPOSITORY_CONTRIBUTORS_SUCCESS = 'FETCH_REPOSITORY_CONTRIBUTORS_SUCCESS';

export const FETCH_REPOSITORY_TOPICS_REQUEST = 'FETCH_REPOSITORY_TOPICS_REQUEST';
export const FETCH_REPOSITORY_TOPICS_SUCCESS = 'FETCH_REPOSITORY_TOPICS_SUCCESS';
